name: Angular CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:


     - name: Cache dependencies
       id: cache-deps
       uses: actions/cache@v3
       with:
         path: |
           node_modues
         key: ${{ runner.os }}-primes
    
     - name: Install dependencies
       if: steps.cache-deps.outputs.cache-hit != 'true'
       run: npm install
       
     - name: Run tests
       run: npm test  
       
     - name: Build Angular app
       run: npm run build 

     
